version: '2'
services:
    etcd:
        container_name: etcd
        image: etcd:v3.1.0-rc.1
        command: |
                etcd --name infra0
                --initial-advertise-peer-urls http://etcd:2380
                --listen-peer-urls http://etcd:2380
                --listen-client-urls http://etcd:2379,http://127.0.0.1:2379
                --advertise-client-urls http://etcd:2379
                --initial-cluster-token etcd-cluster-1
                --initial-cluster infra0=http://etcd:2380
                --initial-cluster-state new
        #ports:
        #   - "2380:2380"
        #   - "2379:2379"
        #   - "4001:4001"

    cattle_manage:
        container_name: cattle_manage
        image: 192.168.86.106/devops/cattle:alpha-v1.4
        command: cattle manage -H tcp://cattle_manage:4000 etcd://etcd:2379
        links:
            - etcd
        ports:
            - "4000:4000"

    cattle_join:
        container_name: cattle_join
        image: 192.168.86.106/devops/cattle:alpha-v1.4
        command: cattle join --advertise=192.168.86.92:2375 etcd://etcd:2379
        links:
            - etcd

    rethinkdb:
        container_name: rethinkdb
        command: rethinkdb --bind all 
        image: 192.168.86.106/develop/rethinkdb:latest

    dface:
       container_name: dface  
       command: |
            controller server --listen :8888 
            -d tcp://cattle_manage:4000 --rethinkdb-addr rethinkdb:28015  --rethinkdb-database "dface" 
       image: 192.168.86.106/develop/dface
       links:
           - rethinkdb
       ports:
           - "8888:8888"
